apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: token-service
  labels:
    app: token-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: token-service
    spec:
      containers:
      - image: wsfdl/token-service
        name: token-service
        ports:
        - containerPort: 22
          name: ssh
        - containerPort: 5000
          name: admin
        - containerPort: 35357
          name: main
