apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-certs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: c9t26470.itcs.hpecorp.net
    path: "/opt/mount1/nfs/certs"
