apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gerrit
  labels:
    app: gerrit
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gerrit
        tier: gerrit 
    spec:
      containers:
      - image: tyrionhuang/vpc-gerrit:latest
        name: gerrit 
        env:
          # $ kubectl create secret generic mysql-pass --from-file=password.txt
          # make sure password.txt does not have a trailing newline
        - name: http_proxy
          value: http://web-proxy.jpn.hp.com:8080
        - name: https_proxy
          value: http://web-proxy.jpn.hp.com:8080
        - name: DATABASE_TYPE
          value: mysql
        - name: DB_ENV_MYSQL_DB
          value: reviewdb
        - name: DB_ENV_MYSQL_PASSWORD
          value: gerrit2 
        - name: DB_ENV_MYSQL_USER
          value: gerrit2 
        - name: DB_PORT_3306_TCP_PORT
          value: "3306"
        - name: DB_PORT_3306_TCP_ADDR
          value: 10.254.0.3
        - name: AUTH_TYPE
          value: LDAP
        - name: LDAP_ACCOUNTBASE
          value: ou=People,o=hp.com 
        - name: LDAP_SERVER
          value: ldaps://ldap.hp.com 
        - name: LDAP_GROUPBASE 
          value: ou=Groups,o=hp.com
        - name: LDAP_ACCOUNTPATTERN
          value:  (&(objectClass=person)(mail=${username}))
        - name: LDAP_ACCOUNTSSHUSERNAME
          value: ${mail.localPart}
        - name: WEBURL
          value: http://c9t26283.itcs.hpecorp.net:30113
        - name: LISTEN_ADDR
          value: "*:29418"
        - name: ADVERTISED_ADDR
          value: "*:30828"
        - name: SMTP_SERVER
          value: c9t21382.itcs.hpecorp.net
        - name: SMTP_FROM
          value: "(Gerrit Code Review) <gerrit@c9t26323.itcs.hpecorp.net>"
        - name: GERRIT_INIT_ARGS
          value: " --install-plugin=download-commands --install-plugin=replication --install-plugin=reviewnotes --install-plugin=singleusergroup --install-plugin=commit-message-length-validator"
        ports:
        - containerPort: 8080 
          name: gerrit-http 
        - containerPort: 29418 
          name: gerrit-tcp
        volumeMounts:
        - name: gerrit-glusterfs
          mountPath: /var/gerrit/review_site
      volumes:
      - name: gerrit-glusterfs
        glusterfs:
          endpoints: glusterfs-cluster
          path: gerrit-glusterfs
