apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: c9t26470.itcs.hpecorp.net
    # path: "/opt/mount1/nfs/gerrit"
    # server: localhost 
    path: "/opt/mount1/nfs/mysql"
    # path: "/mnt/nfs"
