# Gerrit nfs storage PV & PVC

# PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-gerrit
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: c9t26470.itcs.hpecorp.net
    path: "/opt/mount1/nfs/gerrit"

---
# PVC
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-gerrit
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
