apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gerrit-mysql
  labels:
    app: gerrit
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gerrit
        tier: mysql
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        env:
          # $ kubectl create secret generic mysql-pass --from-file=password.txt
          # make sure password.txt does not have a trailing newline
        - name: MYSQL_ROOT_PASSWORD
          value: mysql
          # valueFrom:
          #  secretKeyRef:
          #    name: mysql-pass
          #    key: password.txt
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: nfs-mysql
