# mysql storage

# PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: c9t26470.itcs.hpecorp.net
    path: "/opt/mount1/nfs/mysql"

# PVC
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-mysql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
